branches:
  only:
    - master

language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO="django>=1.4,<1.5" SETTINGS=sqlite3
  - DJANGO="django>=1.4,<1.5" SETTINGS=postgresql_psycopg2
  - DJANGO="django>=1.5,<1.6" SETTINGS=sqlite3
  - DJANGO="django>=1.5,<1.6" SETTINGS=postgresql_psycopg2
  - DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=sqlite3
  - DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=postgresql_psycopg2

matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=sqlite3
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=postgresql_psycopg2

before_script:
  - if echo $SETTINGS | grep 'postgresql' -q; then psql -c 'create database tenancy;' -U postgres; fi

install:
  - pip install $DJANGO coverage django-coverage -q --use-mirrors
  - if echo $SETTINGS | grep 'psycopg2' -q; then pip install psycopg2 -q --use-mirrors; fi

script:
  - django-admin.py test_coverage tenancy --pythonpath=`pwd` --settings=test_settings.$SETTINGS -v2